<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0K9D30A2" failures="1" tests="3" name="Test" time="17.768" errors="0" timestamp="2022-07-27T00:52:56 IST">
  <testcase classname="TestClasses.VerifyUserCanLogin" name="verifyUserCanLogin" time="2.331"/>
  <testcase classname="TestClasses.VerifyUserCanNewAddress" name="verifyUserCanGoToProfilePage" time="6.554"/>
  <testcase classname="TestClasses.VerifyUserCanNewAddress" name="veryUserCanChangeAddress" time="2.051">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestClasses.VerifyUserCanNewAddress.veryUserCanChangeAddress(VerifyUserCanNewAddress.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- veryUserCanChangeAddress -->
</testsuite> <!-- Test -->
